version: 2

updates:

    -   package-ecosystem: "composer"
        directory: "/"
        schedule:
            interval: "daily" # Check for updates daily
        commit-message:
            prefix: "chore" # Prefix for commit messages
        allow:
            -   dependency-type: "all" # Allow both: direct and indirect updates for all packages
        ignore:
            -   dependency-name: "symfony/"
                update-types:
                    - "version-update:semver-major"
        open-pull-requests-limit: 10 # Limit pull requests opened by Dependabot
        groups:
            symfony:
                patterns:
                    - "symfony/*" # Update all Symfony dependencies together

    -   package-ecosystem: "composer"
        directories:
            - "/tools/.php-cs-fixer/"
            - "/tools/.phpstan/"
            - "/tools/.phpunit/"
            - "/tools/.twig-cs-fixer/"
        schedule:
            interval: "daily" # Check for updates daily
        commit-message:
            prefix: "chore" # Prefix for commit messages
        allow:
            -   dependency-type: "all" # Allow both: direct and indirect updates for all packages
        open-pull-requests-limit: 10 # Limit pull requests opened by Dependabot

    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily" # Check for updates daily
        open-pull-requests-limit: 10 # Limit pull requests opened by Dependabot
