#!/bin/bash
# This file was created automatically by cotor as a tool wrapper.

DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

composer install --working-dir=$DIR/.twig-cs-fixer --quiet
exec $DIR/.twig-cs-fixer/vendor/bin/twig-cs-fixer "$@"
