name: Lint
run-name: Workflow started by @${{ github.actor }}

on:
    pull_request:

env:
    fail-fast: true

permissions:
    contents: read

jobs:
    linters:
        name: PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}
        runs-on: ${{ matrix.operating-system }}
        continue-on-error: false

        strategy:
            matrix:
                operating-system: [ 'ubuntu-latest' ]
                php-version: [ '8.2', '8.3' ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    extensions: "intl"
                    php-version: ${{ matrix.php-version }}
                    tools: composer:v2

            -   name: Set composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
                shell: bash

            -   name: Cache composer
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install dependencies
                run: composer install --ansi --no-interaction --no-progress

            -   name: Lint YAML files
                run: ./bin/console lint:yaml config --parse-tags

            -   name: Lint TWIG templates
                run: ./bin/console lint:twig templates --env=prod

            -   name: Lint Parameters and Services
                run: ./bin/console lint:container --no-debug

            -   name: Lint Composer config
                run: composer validate --strict

            -   name: Check if any dependencies are compromised
                run: composer audit

            -   name: Run PHP-CS-Fixer
                run: tools/php-cs-fixer fix --diff --dry-run

            -   name: Run Twig-CS-Fixer
                run: tools/twig-cs-fixer check --no-cache

            -   name: Run PHPUnit
                run: tools/phpunit

            -   name: Run PHPStan
                run: tools/phpstan analyze
